export const users = [
    {id: 1, name: "Jatin", email: "jatinsharma@gmail.com"},
    {id: 2, name: "Jatin1", email: "jatinsharma1@gmail.com"},
    {id: 3, name: "Jatin2", email: "jatinsharma2@gmail.com"},
    {id: 4, name: "Jatin3", email: "jatinsharma3@gmail.com"},
    {id: 5, name: "Jatin4", email: "jatinsharma4@gmail.com"},
    {id: 6, name: "Jatin4", email: "jatinsharma4@gmail.com"},
    {id: 7, name: "Jatin4", email: "jatinsharma4@gmail.com"},
    {id: 8, name: "Jatin4", email: "jatinsharma4@gmail.com"},
    {id: 9, name: "Jatin4", email: "jatinsharma4@gmail.com"},
    {id: 10, name: "Jatin4", email: "jatinsharma4@gmail.com"},
    {id: 11, name: "Jatin4", email: "jatinsharma4@gmail.com"},
    {id: 12, name: "Jatin4", email: "jatinsharma4@gmail.com"},
    {id: 13, name: "Jatin4", email: "jatinsharma4@gmail.com"},
    {id: 14, name: "Jatin4", email: "jatinsharma4@gmail.com"},
    {id: 15, name: "Jatin4", email: "jatinsharma4@gmail.com"},
]